apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nginx
  description: this be nginx
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=ingress-nginx'
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: artist-engagement-portal
